# Generated by Django 6.0.5 on 2026-05-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BibliographyReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("authors", models.CharField(blank=True, max_length=255)),
                ("source_info", models.CharField(max_length=255)),
                (
                    "ref_type",
                    models.CharField(
                        choices=[
                            ("dataset", "Dataset"),
                            ("article", "Article"),
                            ("framework", "Framework/Library"),
                        ],
                        default="article",
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
