name: sr3urban
description: PFA — Super-Résolution d'Images Satellitaires Urbaines par SR3
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  percent_indicator: ^4.2.3
  url_launcher: ^6.2.2
  flutter_staggered_animations: ^1.1.1
  lottie: ^3.0.0
  shimmer: ^3.0.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true   # ← generate: true supprimé